services:
  snippet-permissions:
    container_name: "snippet-permissions"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PERMISSIONS_HOST: ${POSTGRES_PERMISSIONS_HOST}
      POSTGRES_PERMISSIONS_PORT: ${POSTGRES_PERMISSIONS_PORT}
      NEW_RELIC_AGENT_ENABLED: false

  postgres-permissions:
    container_name: "postgres-permissions"
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-permissions-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres-permissions-data: