services:
  database:
    container_name: "permissions-db-dev"
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    container_name: "permissions-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8083'

volumes:
  db-data: